[YOLOWeights]
; 模型路径
weights_path = ./weights/yolov8n.pt

[LogConfig]
; 日志路径
log_path = ./log/run.log

[ModelConfig]
; 滤波次数可选：1(不滤波)、2(默认)、3、5
filter_nums = 2
; 视频流设置宽、高为指定分辨率
width = 960
height = 540
; 前进、后退及转向阈值
s1 = 0.22
s2 = 0.35
d1 = 0.15

